name: CI/CD

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

permissions:
  contents: read
  pull-requests: write # PR 생성 권한 추가

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: feature/automated-pr
          title: 'Automated Pull Request'
          body: '자동으로 생성된 Pull Request입니다.'